import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/session-wrapper";
import Navbar from "@/components/navbar";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TagMyPic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-gray-900 text-white min-h-screen" lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <SessionWrapper>
          <AuthProvider>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <footer className="bg-gray-800 p-4 text-center">
              <p className="text-gray-500 text-sm">
                &copy; 2025 TagMyPic. All rights reserved.
              </p>
            </footer>
          </AuthProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
